### ISSUE TITLE
Events doesn't match standardized signatures.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#10]
Events doesn't match standardized events signatures:
[ETransfer](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L511) 
[EApproval](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L511)
Blockchain explorers wouldn't recognize this token transfers and wouldn't show them.
[ERC20](https://github.com/ethereum/EIPs/issues/20) standard events are: 
`Transfer(address indexed _from, address indexed _to, uint256 _value)`
`Approval(address indexed _owner, address indexed _spender, uint256 _value)`

[ERC223](https://github.com/ethereum/EIPs/issues/223) standard event is:
`Transfer(address indexed _from, address indexed _to, uint256 _value, bytes _data)`

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/16
