### ISSUE TITLE
module: _replaceModule uses send() method to transfer balance

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#100]
If any of the future modules decide to implement a fallback function, the balance transfer to those modules might fail - `send` executes the fallback function on the destination contract, but the gas is limited to 2300:
[https://github.com/CORIONplatform/solidity/blob/master/module.sol#L99](https://github.com/CORIONplatform/solidity/blob/master/module.sol#L99)

As explained in [http://www.blunderingcode.com/writing-secure-solidity/](http://www.blunderingcode.com/writing-secure-solidity/), a possible solution could be using:
```
 require( newModuleAddress.call.value(this.balance)() );
```

**Comment by iFA88** [comment]
I think the gas is not limited to 2300. Where you got that?

**Comment by Dexaran** [comment]
This is **critical**: https://github.com/CORIONplatform/solidity/blob/master/module.sol#L98-L100

If there will be no `function() payable { }` in any module then the replacement will fail!

**Comment by Dexaran** [comment]
@iFA88 `.send` provides 2300 gas. It's true.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/106
