### ISSUE TITLE
ICO will fail to receive ether if it is sent by a contract using send()

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#102]
Maybe it is non-issue, but the callback function  in ICO contract [https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L288-L295](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L288-L295) would consume more than 2300 gas. So any ether `send()` from another contract will fail. 

[http://solidity.readthedocs.io/en/develop/contracts.html#fallback-function](http://solidity.readthedocs.io/en/develop/contracts.html#fallback-function)

**Comment by iFA88** [comment]
If a normal address or a contract calls the fallback function, it need specific gas. This GAS limit is declared who sends the transaction. I think 300k gas is safe for this function!
