### ISSUE TITLE
It is impossible to extend ICO if the icoDelay will be exceeded

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#104]
Due to [this requirement](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L217) you will be unable to extend ICO if the current block number is higher than `icoDelay`. https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L382

**Comment by iFA88** [comment]
Thats right, we can extend ICO only during the ICO.
