### ISSUE TITLE
ICO set etcusd rate delay

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#109]
https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L196-L209

I don't see any reasons of having [this requirement](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L206). If you will set the price rate manually then in case of a mistake there will be wrong pricerate for next 720 blocks.

Why did you limited the opportunity to change price rate at any moment of time?

If you think that this is a question of trust then it doesn't solved it. The user should still trust that you will not make a mistake when changing price. Even more if you *make* an error you can not fix it for 720 blocks.

**Comment by iFA88** [comment]
We know about that, thank for your feedback. It is ok for us.
