### ISSUE TITLE
Use case of check in approval

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#110]
What is the use case of [this check](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L157)?

The user can not approve more than he has on balance. If user A has 100 tokens he can approve user B 100 tokens and user C 100 tokens. So the total amount of approved funds will be 200 tokens.

So why the user can not approve more than he has to one address, but can approve more than he has to two different addresses?

**Comment by iFA88** [comment]
We have discussed it and we accept your suggestion!
