### ISSUE TITLE
Calculations safety.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#111]
Examples:

https://github.com/CORIONplatform/solidity/blob/master/multiOwner.sol#L87
https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L148
https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L139

Every `+` , `-` , `/` , `*` , `+=` , `-=` operation could be replaced with safeMath function.

**Comment by iFA88** [comment]
On way!
