### ISSUE TITLE
Question: Is there any reason why token<-> ICO relation is not implemented through ModuleHandler?

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#117]
It seems that the idea of ModuleHandler was  to take care of a communication among the modules? So, for example the Token could call ModuleHandler to figure out if ICO is ongoing or not. 
Also if ICO was a normal module, it could also process Transfer events to figure out changes in InterestDB etc. - that would reduce the coupling among the modules.

On the other hand - I guess the change might be too big at the current stage.

**Comment by iFA88** [comment]
`ICO` can directly communicate with `token` and `premium` I think this is ok now. :)
