### ISSUE TITLE
No way to to change exchange address in the Token contract

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#118]
I have a few issues/questions in regards to an exchange address stored in the Token contract:
- will there always be only one exchange contract?
- maybe it would be good to be able to change the exchange contract address without replacing the Token contract?
- maybe (that is a bigger change) it would be good to separate transaction fee calculation to another contract? Then the Token need not even know the exchange addresses - it would only need to know the Fee  Calculation contract. 
 - Or maybe exchange addresses could be retrieved from module handler?

**Comment by iFA88** [comment]
We have discussed that. The first plan was that the users who buying ether only for gas ( above 0.2ETC ) we don't charge any fee. But I will now remove hard coded exchangeAddress for that.

**Comment by Dexaran** [comment]
I agree. The central controlling unit of the system is `moduleHandler`. It would be better to receive exchange address from `moduleHandler` contract.
