### ISSUE TITLE
moduleHandler: configureModule contains nasty code but still works

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#120]
The `configureModule` function uses `schelling` contract to call `configure` method on `token` and `provider` contracts - [https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L427](https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L427)

It looks nasty, but it works as long as the `token` and `provider` contracts define the `configure` or a `fallback` function.

I guess a nicer way would be to add default `configure` function to `module` and to `abstractModule`.

**Comment by iFA88** [comment]
Have soon done in https://github.com/CORIONplatform/solidity/blob/iFA-FIX . Modules have now standard `configureModule` function.
