### ISSUE TITLE
Abort ICO - leaves token and premium contracts uninformed about the event

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#121]
If `abortICO()` is called, the `token` and `premium` contracts are not informed about it and they still think that ICO is ongoing:
- no transaction fee will be charged
- only genesis addresses will be allowed to make transfers

Not sure if it is a problem or not?

**Comment by iFA88** [comment]
Yeah, `token` and `premium` will think its forever ICO, we (genesis addresses) can only transfer tokens. I dont see any problem.
