### ISSUE TITLE
Abort ICO - 10% of ICO contract Ether balance is trapped/lost

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#122]
After `abortICO()` is called there is no way for Foundation to receive it's 10% of ICO contract Ether balance. Only ICO investors are allowed to receive their 90% of the Ether paid. 
So, 10% of ICO contract balance stay locked in  the contract.

**Comment by Dexaran** [comment]
10% of the ICO funds would be instantly delivered to the foundation at the moment of token purchase. Not after the end/abort of the ICO.
https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L269

**Comment by gundas** [comment]
Yes, you are right.
