### ISSUE TITLE
provider.sol -  function provider (wrong argument count for modifier invocation) ?

### ISSUE THREAD

**Issue by jmsanta** [CORIONplatform/solidity#128]
compiling this file I get an error that says :  wrong argument count for modifier invocation, 

**1 argument is given but expected 0**

If I Put :  function provider(address moduleHandlerAddress) {}

Or  function provider(address moduleHandlerAddress) module() {}

I get a Warning only.

**Comment by iFA88** [comment]
Provider is still in development and will be full recoded, but thank you for your issue.
Please for the bug bounty review use `bugBounty` branch.

**Comment by jmsanta** [comment]
thanks, I will check for more sofisticated errors,

but can you provide the way to report it ?
I change to the  bugBounty branch. but the issues are all mixed in the same tab?
sorry :(

**Comment by iFA88** [comment]
Yes the issues are mixed but this is not the problem. You need check the .sol files inside the `bugBounty` branch. If you have any bug found you can open an issue for that.
