### ISSUE TITLE
provider.sol - wrong argument count

### ISSUE THREAD

**Issue by jmsanta** [CORIONplatform/solidity#129]
revision https://github.com/CORIONplatform/solidity/commit/288f401a9f415d9932ef51b7651fdf19d2a2550c

I get an error compiling this file  : provider.sol

wrong argument count  ( expected 0 )

if you change code to : 
contract provider is module {
    function provider(address) module() {}
}

there is no error or warning.

**Comment by iFA88** [comment]
Thank you, please use `bugBounty` branch!
