### ISSUE TITLE
The transferAndCall function is superfluous

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#14]
[This](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L281) function is superfluous. If you will try to transfer tokens into a contract via `transfer` then `transferToContract(msg.sender, _to, _amount, _extraData);` will be called. This function is doing the same.
If you will try to call `transferAndCall` to transfer tokens to an address then the transaction will always fail.

**Comment by iFA88** [comment]
No, its not. With the `transfer` function I can send any Data with the call.

**Comment by Dexaran** [comment]
`transfer` function is calling `transferToContract` if the destination address is a contract.
`transferAndCall` is calling `transferToContract` function too.

You can send any Data with both `transfer` and `transferAndCall` functions. They are similar.

**Comment by iFA88** [comment]
With this function is no way to send any data:
```javascript
function transfer(address _to, uint256 _amount) isReady external returns (bool) {
```

**Comment by Dexaran** [comment]
I think it is a flaw of structure of the contract.

`transfer` function should contain _Data. 
event `Transfer(address indexed from, address indexed to, uint amount, bytes Data);` should log _Data to blockchain.
The function `transferAndCall` shouldn't exist.

**Comment by iFA88** [comment]
Alright, I will use that.
