### ISSUE TITLE
provider-recode code structure

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#140]
Hello,

I understand this is a matter of preference.

I think the readability of the code would improve if:
- `providerDB` would be separated into another file
- I do not see much added value of wrapping each `providerDB` function in the `provider` contract. It (mostly) does not do anything else besides calling the 'providerDB'. I think it makes the code much less readible without adding anything useful (`providerDB` could be re-coded to fail if the function does not succeed instead of always returning `success=true`).

**Comment by iFA88** [comment]
Hi!

I code in remix (browser solidity) if I have the `providerDB` in a separate file, I can not use highlighting what I use very common. Sadly the search (CTRL+F) is really buggy. BUT yes, when I'm done its nice to have in an separated file.
In the `provider` contract I have created internal functions for each `providerDB` as you see. This is important to 'catch' the errors and I don't need check the `success` some function who I call DB function. I think, I don't have any function in the `provider` what I don't use, but if you find one please let me know :)
The `success` variable is very important from an "third party" contract.
