### ISSUE TITLE
CheckReward: resets owner's clientPaidUpto to zero

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#142]
I think that in case a client (not owner) is calling the `CheckReward` function the owner's clientPaidUpTo will be reset to zero because of this line: [https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1152](https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1152)

**Comment by iFA88** [comment]
Yeah this is fixed soon, but you have nice eyes :)
```
        _setClientLastPaidRate(client, data.rate);
        if ( data.setOwnerRate ) {
            _setClientLastPaidRate(data.owner, data.rate);
        }
```
I work every day on the contract but i don't upload to github. Please skip now the `checkReward` function because I change it in every hour.

**Comment by iFA88** [comment]
Yes you have right, I will check that in the current code!
