### ISSUE TITLE
CheckReward: strange if condition

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#143]
In `CheckReward` function within the loop there are 3 checks with  the following  condition:
```if ( ! ( data.isForRent && data.clientPaidUpTo > data.roundID ) ) {```

If `data.isForRent = false` then the  _if check_ above will always evaluate to `true`, no matter what are the values of `data.clientPaidUpTo` and `data.roundID`.  It does not seem right...

**Comment by iFA88** [comment]
Hmm.. I will check that!

**Comment by iFA88** [comment]
Fixed, thanks :)
