### ISSUE TITLE
setProviderDetails(...) admin has to always reset admin to 0x00

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#145]
[https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L954-L956](https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L954-L956)

if _admin_ user calls the `setProviderDetails(...)` function, he has to supply argument `admin=0x00`. The intention is that _admin_ cannot change `admin` of the provider. However, as a result of such call, the `admin` of the provider will be set to `0x00`. So the _admin_ user will kind of  "lock himself out" if he ever tries to update the provider details.

**Comment by iFA88** [comment]
Nice catch!
Have changed the code, please review it.
