### ISSUE TITLE
checkReward(...) - owners reward vs. user reward timing

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#148]
Let's say I have a public provider with one user connected who has _10000 CORION_. The provider gives 50% of schelling reward to connected  users.
Let's say there have been 3 schelling  rounds with emission rates 2.5%, 2.5% and 0%.
If the user gets his rewards after these 3 schelling rounds above, my public provider connected capital will be:

- 1st schelling round: `10000`
- 2nd schelling round: `10000 + 10000*0.025*0.5 = 10125`
- 3rd schelling round: `10125 + 10125*0.025*0.5  = 10251.56`

If the owner of this public provider calls `checkReward(...)` before the connected user, the owner will not get the schelling reward for the extra _125 CORION_ connected capital for the second schelling round. However, if the owner calls  `checkReward(...)`  after the user, he would receive extra `125*0.025*0.5 = 1.5625` _CORION_.

Not sure if this is a problem or not.

**Comment by iFA88** [comment]
I understand what you say. There is no compound interest for calculating reward.
The balance (supply) is only matter when the Schelling round ends.
Emission/release comes from the total token supply and its fix 0.3% if we release tokens on that Schelling round.
