### ISSUE TITLE
checkReward(...) function declared constant

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#149]
[https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1431](https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1431)

the current implementation of [checkReward(...) function](https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1070) does modify state (is not idempotent).

**Comment by iFA88** [comment]
Yes, because we want only to check the rewards. What is the problem with that?

**Comment by gundas** [comment]
I am not sure if it is a problem - a constant function is a promise not to modify any state. 
Works in Remix.

**Comment by iFA88** [comment]
Sorry, I still don't understand what is the problem.
The `checkReward` should not do any change on the blockchain, this is why that are `constant`.
