### ISSUE TITLE
CheckReward(...): When admin is also client, the ClientPaidUpTo is incremented twice

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#152]
In `CheckReward(...)` when admin is also client, the ClientPaidUpTo is incremented twice within the main loop:
[https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1159-L1162](https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1159-L1162)
and
[https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1233-L1236](https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L1233-L1236)

**Comment by gundas** [comment]
My bad - it is  not incremented twice, it is just set twice to the same value.

**Comment by iFA88** [comment]
If you debugging, the `DEBUG` event is very useful :)
