### ISSUE TITLE
provider.sol: owned.sol import

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#153]
It is a small thing.

`provider.sol` imports 'owned.sol'
`providerDB` in 'provider.sol' extends the `owned` contract. However, the `owned.sol` does not define the `owned` contract. It contains the only contract called `ownedDB`. 

Shouldn't the `providerDB` extend `ownedDB`?

**Comment by iFA88** [comment]
?
I don't see any `ownerDB` contract.

**Comment by gundas** [comment]
[https://github.com/CORIONplatform/solidity/blob/provider-recode/owned.sol#L3](https://github.com/CORIONplatform/solidity/blob/provider-recode/owned.sol#L3)

Ok, but I get it - the other files in provider-recode branch are out of  date.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/search?utf8=%E2%9C%93&q=ownerDB&type=
I don't get any founds, interesting..
Please forget the `provider-recode` branch and check the `rc`. Thank you!
