### ISSUE TITLE
It is possible  to create provider for rent without an admin

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#154]
If I create a new provider `IsForRent=true` and `admin=msg.sender`, the check will pass:
```
        require( ( ! isForRent ) || ( isForRent && admin != 0x00) );
```

but the admin will be set to 0x00 later in internal `_openProvider(...)` function.

**Comment by iFA88** [comment]
Nope :)
https://github.com/CORIONplatform/solidity/blob/provider-recode/provider.sol#L701-L703

**Comment by iFA88** [comment]
You have right, if anyone opens an provider for `isForRent` we need an admin for that!

**Comment by iFA88** [comment]
Please, in the future check the `rc` branch, because this branch would be deployed for next.
https://github.com/CORIONplatform/solidity/tree/rc

Thank you!
