### ISSUE TITLE
The owner of the provider can set himself as an admin

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#155]
The `_openProvider(...)` function checks that the owner does not specify himself as an admin:
```
        if ( admin == msg.sender ) {
            admin = 0x00;
        }
```
However  the owner can set himself as an admin by calling `setProviderDetails(...)`. 
If the Provider has been created  as `IsForRent=true`, the owner will loose his `senderReward` share (he will receive only `adminReward` share).

**Comment by iFA88** [comment]
Yes, you have right!
