### ISSUE TITLE
token _transfer(...) when   amount<balanceOf(from)<(amount + fee)

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#156]
`token.sol` on _rc_ branch:

`_transfer(...)` function handles the cases when `balanceOf(from) == amount` by decreasing the `amount` by `_fee`. However, it does not handle the case when `amount  < balanceOf(from) < amount + fee` - it simply fails the require check:
```
 require( db.balanceOf(from) >= safeAdd(amount, _fee) );
```

Looks kind of inconsistent to me.

**Comment by iFA88** [comment]
You need equal or greater balance as the sending amount with fee. I don't see any problem there.

**Comment by gundas** [comment]
I agree. Thus, my question is why the code additionally handles a special case when `balance == amount`, but not the case when `balance` is greater than `amount` but lower than `amount + fee `

**Comment by iFA88** [comment]
If the address owner want to send her/his balance to an another address, then the fee is subtracted from the sending amount. If we don't have this, the users can not empty an address. :)

**Comment by gundas** [comment]
So, if I want to transfer _amount=100 COR_ and the _fee=5 COR_, then:
- _balance <= 99_, result:**fail**
- _balance = 100_, result:**success**
- _balance = 101_ to _104_, result: **fail** - this seems weird, considering  the success in case above?
- _balance >= 105,_ result: **success**

**Comment by iFA88** [comment]
yes, this is correct. I dont think that schould be weird. This IF is only when the sender want send all of his/her balance. If the balance is 1514717841 ION then he/she need to send 1514717841 ION.
If he/she send1514717840 ION would be failed.

**Comment by gundas** [comment]
The code works as intended - so, I am closing this issue.
