### ISSUE TITLE
Actual claimed provider reward is different from the displayed pending reward amount

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#168]
Hello,

I think someone else complained about a similar situation on telegram channel.

Here is what happened:
1. The account was connected to the same provider all the time
2. Some weeks ago an account received small amount **X** of COR reward from the Provider. This reward was not claimed.
3. After that the account received more COR funds. 
4. There was another emission of Rewards recently, and the Check Reward in the wallet was showing Pending reward **Y** amount of COR. After claiming the rewards only the small **X** amount was transferred to the account (basically gas costed more than the received reward :) )
5. After claiming a reward again the correct amount has been transferred.

......

OK, while writing the above I think I know what happened there - there is a `roundLimit` parameter, which most probably has a different value for the read only `checkReward|(..)` and the `getReward(..)` functions. 
I understand why it is done this way, but it is very very confusing for a user. As a minimum there should be some explanation for the user in case full amount of the reward is not retrieved.

**Comment by iFA88** [comment]
Yes, thats the point. There was more round as the roundLimit and thats way the user have not received the COR. We known about this, I have suggested to display this in the wallet provider claim page, but the whole website is on refactor. So may later, its planed :) Thanks for reporting Gundas!
