### ISSUE TITLE
Corrupted logic. allowance_ is stored at replaceable contract.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#20]
If the token.sol and premium.sol contracts are used as statically-linked libraries for function storage, whereas the tokenDB.sol contract is used as a state store (it stores the balances), I think that `allowance_` should also be stored in tokenDB.sol.

In this case, replacing any library contract that implements logic of token functions will not affect any state. Allowances wouldn't be destroyed when replacing a contract.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/23
