### ISSUE TITLE
Small fixes.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#21]
1. [var fee](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L380) should be `uint256 fee`. Strong typization is preferable whenever possible. Let's not rely on compiler behavior. It is not safe. [gcc compiler](https://en.wikipedia.org/wiki/GNU_Compiler_Collection) is under development for 30 years. The Solidity compiler has been in development for about 2 years, so it's very new, and I'm sure it contains errors. Let's not rely on compiler behavior if it is possible.

2. It does not check whether `shellingAddr` is found or not: https://github.com/CORIONplatform/solidity/blob/master/token.sol#L384
`schF` is declared, but not used.

**Comment by iFA88** [comment]
1. https://github.com/CORIONplatform/solidity/blob/master/token.sol#L398
If the transaction returns are exactly declared then the var does the same declaration. (tested with uint8..256 etc)

2. The procedure returns 3 variable, I need to declare every three variable if i even use only 2.

**Comment by Dexaran** [comment]
1. Yes, it is working in this case but you should never use `var` when you can use a direct type definition.
Rationale: obstructed logic, hard-to-read code, 
More `var` definitions the code contains, more difficult it is to verify this code. Also it will be more difficult to find an error if it will occur in future and you will be needed to fix it as soon as possible.

2. If the `Schelling` module is not found then `schellingAddr` would be equal to `0x00` and [burn(_addr, _fee](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L394) would be executed. I think it is correct behavior. Am I right?

**Comment by iFA88** [comment]
1. Yes i have replaced every `var` who i directly declare a variable, but when the function declares than it is safe.

2. When the Schelling module are missing (i dont know why should that) then the `schellingAddr` is 0x00, `schF` is FALSE and s are TRUE. I check only the `schellingAddr` If we dont have any schelling game, the whole fee should burn.
