### ISSUE TITLE
Check the possibility of a transaction.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#22]
I think that there should be a check of the possibility of the transaction. If the user sends less than `transactionFeeMin`, the transfer must be thrown.

https://github.com/CORIONplatform/solidity/blob/master/token.sol#L326

Example code:
```js
    function transfer_(address _from, address _to, uint256 _amount, bool _fee) internal {
        if(_fee) {
           require( db.balanceOf(_from) >= _amount + getTransactionFee(_amount) );
        }
        require( _from != 0x00 && _to != 0x00 && _to != 0xa636a97578d26a3b76b060bbc18226d954cf3757 );
        require( ( ! isICO) || genesis[_from] );
        require( db.decrease(_from, _amount) );
        require( db.increase(_to, _amount) );
        if ( _fee ) { _processTransactionFee(_from, _amount); }
        if ( isICO ) {
            require( ico(icoAddr).setInterestDB(_from, db.balanceOf(_from)) );
            require( ico(icoAddr).setInterestDB(_to, db.balanceOf(_to)) );
        }
        require( moduleHandler(super._getModuleHandlerAddress()).broadcastTransfer(_from, _to, _amount) );
}
```
EDIT: corrected required condition

**Comment by iFA88** [comment]
I think (like on any crypto currency) anyone can send lower amount as the transaction fee.

**Comment by Dexaran** [comment]
I see that fee will be subtracted from senders balance.
Imagine that the Alice wants to execute [transfer](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L199) `transfer(Bob, 400000000)` while Alice has only 400079999 COR at balance. Fee will be 80000 COR. Alice has not enough funds to perform a transaction and pay fee. The transaction will fail anyways but I think we need to perform a check for this.
```js
        if(_fee) {
            require( db.balanceOf(_from) >= _amount + getTransactionFee(_amount) );
        }
```
Rationale:
If the condition of `require( db.balanceOf(_from) >= _amount + getTransactionFee(_amount) );` is not met then the instruction `0xfd` will be performed (`REVERT` opcode) and unspent gas would be refunded. The transaction will fail with "Input-related error".

If this artificial check wouldn't be implemented, then:
1. [transfer(Bob, 400000000)](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L199) will be executed
2. internal [transfer_(Alice, Bob, 400000000, true)](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L214) will be executed
3. [db.decrease(Alice, 400000000)](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L341) will be executed (Alice will now have 79999 on balance)
4. [_processTransactionFee(Alice, 80000)](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L343) will be executed successfully
5. [db.decrease(Alice, 64000)](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L387) will be executed successfully
6. [burn_(Alice, 16000)](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L389) will be executed
7. [db.decrease(Alice, 16000)](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L461) will lead to execution of decrease in db
8. [safeSub(balanceOf[Alice], 16000);](https://github.com/CORIONplatform/solidity/blob/master/tokenDB.sol#L40) will lead to execution of safeMath
9. [assert(15999 - 16000 > 16000)](https://github.com/CORIONplatform/solidity/blob/master/safeMath.sol#L29) will end with execution of `0xfe` instruction of the EVM (`INVALID` opcode). It will consume all provided gas and the transaction will fail with "Runtime exception: Bad jump destination".

I think that if the user tries to send more than he has, then this is a ""Input-related error", not a "Runtime exception". I also think that the refunding of all gas is better than the consumption of all gas.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/24/commits/f6b6075647eebda3cc4bcc5b88c1bf7717401b4b
