### ISSUE TITLE
Two functions getTransactionFee perform similar actions.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#25]
[getTransactionFee](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L398) and [getTransactionFee_](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L409) functions are completely same.

I think that the pair of these functions could be replaced with a single function:

```js
    function getTransactionFee(uint256 _value) constant returns (uint256 fee) {
        fee = _value * transactionFeeRate / transactionFeeRateM / 100;
        if ( fee > transactionFeeMax ) { fee = transactionFeeMax; }
        else if ( fee < transactionFeeMin ) { fee = transactionFeeMin; }
}
```

**Comment by Dexaran** [comment]
Any use of internal `getTransactionFee` function can also be replaced with a use of this constant returns function.

**Comment by iFA88** [comment]
This two has an important difference!
1. The function with `constant public` will be called like an `external` function (Limited gas forwarded and can be failed etc etc)
2. The function with `internal` will be simple jumped and stay on the same contract code without any risk.

**Comment by Dexaran** [comment]
`constant ` function doesn't consume gas. It can be performed without a transaction sent to a blockchain.
It can also be used to provide a value into executable function.

**Comment by iFA88** [comment]
The `constant` function costumes the same gas if you call from contract or check in your local EVM without transaction (like estimateGas). I write you right away an example contract.

**Comment by Dexaran** [comment]
It seems like we didn't understand each other.
Constant function will:
1. Consume gas when executed like this:
```js
    function func() constant returns (uint256) {}

    function example() {
        a + func();
}
```
2. Does not require a transaction to make a call from outside to watch the result of this function.

We can just use `public constant` function [here](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L337) and [here](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L380). 
Is here any reasons to keep both `internal` and `public` functions while we can merge them into one `constant public` function and use it?

**Comment by iFA88** [comment]
Yes we have miss understood other.
1. Right
2. I have tested now, if you call inside a `constant` function it does not call them, the program code will stay in internal.

So, yes we can use without risk `constant` function inside the same function, it would be equal to like `internal` function.

Right?

**Comment by Dexaran** [comment]
I'm talking about something like #26

**Comment by iFA88** [comment]
Yes me to :)
