### ISSUE TITLE
setICOEthPrice doesnt work. Unable to debug price.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#31]
The price is set to `icoExchangePrevRate` instead of `_value`. https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L217

The `icoExchangePrevRate` is set to `_value` instead of the previous rate of the price before this function execution. https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L218

**Comment by iFA88** [comment]
This is normal behavior!
This is for again abusing ETC price.

If we set `A` to new ETC price, waiting `125` block and set new `B` price then the `A` price will be the current price for the next `125` block. After `125` set again `C` price, then the `B` price would the current price for another `125` block!

Anyone has right to use the price for `125` block.

If we don't have this, can be abuse, with we set the price to `5000000`, send quick a `buy` transaction and we set the price back to normal.

**Comment by Dexaran** [comment]
I prefer not to worry about the opportunity to cheat. The block-chain is intended to solve the issue of trust. Each contract call is transparently available for viewing for each participant.

I see that this check for blocks count is limiting a debugging function of the contract. It can be a problem if something goes wrong.

**Comment by iFA88** [comment]
We would like to have this, but thanks!
