### ISSUE TITLE
A user can become a self affiliate.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#32]
Imagine Alice has two addresses `0xa1` and `0xa2`.
She can execute [buy(0xa1, 0x00)](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L300) to buy 1e12 COR from `0xa1` address.
Then she can execute `buy(0xa2, 0xa1)` and the `0xa1` address will receive additional 5% of COR.

**Comment by iFA88** [comment]
Yes, this is true, but should do that. If you have tips avoiding this please share with us :)
Affiliate rates are 1-5%.
