### ISSUE TITLE
Private variables makes it hard to watch contract state.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#33]
There is a lot of private variables: [tokenAddr](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L38), [nextTokenExchangeRate](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L45), [affiliate](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L55) structure, [totalMint](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L58) and much more.
You should make variables `public` if there is no need to keep them secret. It will make debugging easier.

Imagine that error occurs and you should understand what is causing the error and fix it. If part of the state of contract is hidden, it is much more difficult to understand the error and fix it.

NOTE: I'm not talking about testing before the final version of the contract will be deployed. I'm talking about [debugging](https://en.wikipedia.org/wiki/Debugging) of the contract that will be deployed on mainnet if the error will occur in final version of the contract.

**Comment by iFA88** [comment]
Alright, I will code that soon.

**Comment by iFA88** [comment]
#36
