### ISSUE TITLE
Extra imports.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#35]
To be honest ICO.sol doesn't require [token.sol](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L4), [premium.sol](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L5) and [moduleHandler.sol](https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L6) to be imported.
`abstractToken` is sufficient for the workflow of this contract.

**Comment by iFA88** [comment]
Soon FIXed https://github.com/CORIONplatform/solidity/pull/30
