### ISSUE TITLE
Structure of module contract.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#37]
`module.sol` contract contains only internal functions now (example [_connectModule](https://github.com/CORIONplatform/solidity/blob/master/module.sol#L24)). External module functions are implemented by other contracts independently (example [external connectModule](https://github.com/CORIONplatform/solidity/blob/master/publisher.sol#L12)).
I think that it will be better to implement the external functions inside `module.sol` contract and to inherit them in contracts that are modules.
If you need any specific functionality for these functions (for example, [providers connectModule](https://github.com/CORIONplatform/solidity/blob/master/provider.sol#L12)), then certain functions can be overridden in contracts that are modules.

**Comment by iFA88** [comment]
Yes, we can put some `external` functions into the module.sol, but not every. These externals muss be unique: `connectModule` (provider), `replaceModule`, `transferEvent`, `newSchellingRoundEvent`

**Comment by iFA88** [comment]
I can put `disableModule`, `isActive`, `replaceModuleHandler` to the `module.sol`.

**Comment by Dexaran** [comment]
Unique functions can be overridden in contracts that must have them.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/38
