### ISSUE TITLE
Critical issue. Lack of modules debugging.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#39]
There is no mechanism to debug modules.
If `moduleHandler` is the central control unit of the Corion system, then it must be self-contained without any external dependencies.
In current `moduleHandler` implementation such functions as [newModule](https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L157) and [dropModule](https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L172) depends on `Publisher` contract. It is a structural flaw of the whole system.

It should also be possible to immediately intervene in the system workflow if an error occurs. There is no need to introduce any [delays](https://github.com/CORIONplatform/solidity/blob/master/publisher.sol#L172) or [voting mechanisms](https://github.com/CORIONplatform/solidity/blob/master/publisher.sol#L186). The lack of this mechanism leads to fatal consequences of TheDAO hack. $60,000,000 were stolen due to the fact that the debugging mechanism was not presented in the DAO.

I think that such a mechanism is a "must have" detail of each contract. This is especially relevant for such a complex system as Corion. This mechanism was implemented in [ENS](http://ens.domains) by members of Ethereum Foundation ("Managing the ENS root" section).

The lack of a mechanism that allows Corion developers to intervene instantly into the system workflow and debug the central module without any external dependencies is a critical flaw.

Two main problems:
1. The central controlling unit of Corion contracts system (`moduleHandler` contract) must not have any further dependencies.
2. The mechanism to manually debug modules must be implemented on early stages.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/46
