### ISSUE TITLE
checkOpposited function should be constant returns instead of internal

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#43]
https://github.com/CORIONplatform/solidity/blob/master/publisher.sol#L136

I assume that this function should be `constant returns` instead of `internal returns` since it is not modifying any state but returning is the condition met or not.

Also I don't see any reasons to keep it `internal`. Nothing bad can happen if someone will call it from outside to check the condition.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/commit/5d778c4719d8b87a17ccc07b7f98c77069c49f3c
