### ISSUE TITLE
The absence of updates of the array of announcemens causes extremely high TX fees and the potential impossibility of completing a transaction.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#44]
There is no function to reset the `announcements` array of the` Publisher` contract.

For [this check](https://github.com/CORIONplatform/solidity/blob/master/publisher.sol#L20)
, a lot of calculations are required with the growth of the array of `announcements`. Impossibility of resetting the `announcements` array will cause extremely large TX fees. If the `announcements` array will grow enough this will cause excess of block gas limit. This will stop the whole platform.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/commit/d49cddc6b2e3129005612696c5fea7595115e375
