### ISSUE TITLE
Critical vulnerability. External dependencies of moduleHandler blocks module updates.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#48]
[This function execution requirement](https://github.com/CORIONplatform/solidity/blob/0f5581b5c03960d549b9e1e1a2e30e8c781bdc8c/moduleHandler.sol#L161) will fail if the replaceable `module` does not support the `replaceModule(address)` function, or if the replaceable `module` returns `false`.

If the corrupted module will not return `true` after the execution of `replaceModule` you will be unable to replace this corrupted module. This can lead to the crash of the entire platform.

**Comment by iFA88** [comment]
This would not happens when you connect a tested module to the module handler.
Like the same situation while you plug a burned RAM module to your motherboard and wondering why not boot that. :)

**Comment by Dexaran** [comment]
It is a potential vector of attack.
You can replace any `module` with a corrupted `module`, and you will not be able to restore the platform because you can not replace the corrupted module. It will ruin the whole platform.

Yesterday we saw a [social engineering attack](http://www.ibtimes.co.uk/classic-ether-wallet-has-been-hacked-do-not-use-it-send-currency-1628479).

You can say: "We will never make a mistake here," but if there is an opportunity to do so, then this is a vulnerability.
