### ISSUE TITLE
The approach of development and the coding standard.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#5]
### Abstract
I see that the entire system of Corion contracts is complex enough. I want to remind that the most important points in the development of such a system is the writing of error-free code. The code of contracts should contain no errors.

1. The main goal is to minimize the probability of error or misunderstanding of the logic of contract codes to improve the fault tolerance of the entire system.
2. The code should be easy to read.
3. Expressions should be as simple and basic as possible.
4. The logic of the code should be as straight as possible. A very important goal is to keep invariantness of the code.

### Motivation
I think that current implementation code style is potentially dangerous and can lead to ambiguous interpretation of code logic. To improve the fault tolerance of the code, [strong typing](https://en.wikipedia.org/wiki/Strong_and_weak_typing) is preferred. The syntax of the code should minimize choices of ways to perform basic operations. A good example of programming language that was specially designed for development of systems that should be maximally fault-tolerant (such are avionics and Department of Defense programms) is [ADA programming language](https://en.wikipedia.org/wiki/Ada_(programming_language)#Features) that supports extremely strong typing.

### Inference

Such expressions should be avoided: 
```js
 var (success, back) = tPCA(_to).receiveCorionToken(_from, _amount, _extraData); 
```
Rationale: weak typing, ambiguous interpretation of logic, `back` variable definition is not clear. 
Preferable:
```js
 if(!tPCA(_to).receiveCorionToken(_from, _amount, _extraData)) { throw; } 
```
OR
```js
 bool returnedValue = tPCA(_to).receiveCorionToken(_from, _amount, _extraData);
```

Such expressions should be avoided:  
```js
 require(a = b);
 ```
Preferable: 
```js
 if(a != b) { throw; }
 ```
Rationale: there is a choice of ways ( `require (a=b)` VS `if(a!=b) { throw; }` ), readability of the code
`require(a = b);` assumes that programmer that will read the code must know how `require` works on Ethereum while `if(a != b) { throw; }`  is definitely clear for every programmer.

Addition: All functions should have the same behavior.
`require(a = b);` is always `throw`ing when `a` is not equal to `b`, but there are some functions in contracts that are returning `false` instead of throwing. My personal opinion is that throwing is preferable instead of returning false in all cases.

This is not a critical vulnerability, but I've found it important to remind.

**Comment by iFA88** [comment]
First, thank you for your work.

We need to use
```javascript
var (success, ret) = somefunction(someinput);
```
because the `ret` can be an valid zero.

The `require` or `thow` difference is only personal a style :)

**Comment by Dexaran** [comment]
I just report everything that I find strange. You can take into account my opinion or not - this is your choice.
