### ISSUE TITLE
Compiler-related errors with 0.4.12-nightly.2017.6.23+commit.793f05fa and higher versions of Remix solidity compiler.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#56]
0.4.11 compiler works fine.
0.4.12 throws an error. (https://github.com/Dexaran/solidity/tree/master/Compiler-Errors)

I don't know if this is a bug in the 0.4.12 compiler or 0.4.11 compiler doesn't throw an error when it should do it.

**Comment by iFA88** [comment]
We should stay on 0.4.11. We should not use beta releases for that.
