### ISSUE TITLE
Function name typo

### ISSUE THREAD

**Issue by nGoline** [CORIONplatform/solidity#66]
Not a bug per se but there's a name typo on the exchange.sol file on line 124.

`function nomraliseRate(uint256 rate) internal returns (uint256 nRate) {`
should be
`function normalizeRate(uint256 rate) internal returns (uint256 nRate) {`

The function is called on the same file at lines:
204: `_rate = nomraliseRate(rate);`
213: `_rate = nomraliseRate(rate);`
252: `_rate = nomraliseRate(rate);`
265: `_rate = nomraliseRate(rate);`

**Comment by iFA88** [comment]
Thank you very much! The `exchange`, `schelling`, `provider` contracts are not deep tested. The `provider` will be completely recoded, I currently working on it.
