### ISSUE TITLE
Approval error. Check mistakes. 

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#7]
There are three checks when approving someone to withdraw tokens from `msg.sender`. [Check for selfapproval](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L174) , [check for approving more than has on balance](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L175) , [check for transactionCount](https://github.com/CORIONplatform/solidity/blob/master/token.sol#L176).

1. `msg.sender` is now unable to approve someone to withdraw tokens. `msg.sender` can approve himself to withdraw tokens.
I assume that `if( msg.sender == _spender ) { return false; }` should be used instead of
 `if( msg.sender != _spender ) { return false; }` if you want to disallow users to approve themselves.

2. At current implementation the user can only approve **more** than he currently has on balance. If you want to disallow users to approve more than they currently have on balance then 
`if( db.balanceOf(msg.sender) < _amount ) { return false; }` should be implemented instead of
 `if( db.balanceOf(msg.sender) >= _amount ) { return false; }`.

3. `_transactionCount ` is now a dummy variable that never changes.

I will also recommend to `throw` instead of returning `false`. When you return `false`, the transaction will be sent successfully, but no changes will be applied to the blockchain, while `throw` will roll back the transaction if an error occurred.

**Comment by iFA88** [comment]
1 & 2. You have right, i will fix this ASAP.
3. https://github.com/CORIONplatform/solidity/blob/master/token.sol#L239
