### ISSUE TITLE
Keep variables public if there is no need to make them secret.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#70]
As I've wrote earlier : https://github.com/CORIONplatform/solidity/issues/33
Private variables makes it hard to watch contract state. You should make variables `public` if there is no need to keep them secret. It will make debugging easier.

This is a hidden variable : https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L38
https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L56
https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L85
https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L238-L242
https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L246

**Comment by iFA88** [comment]
Schelling will be recoded with the "new" style!
