### ISSUE TITLE
Hidden logic. Variable names do not display their use. Readability of the code.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#72]
https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L210

Variable names should make their use understandable to the programmer who will read this code. Please, name variables to make logic of the contract explicit. Keep the code readable.

This will reduce the possibility of an error when the auditor or bug hunter has missed the error due to terrible code readability.

**Comment by iFA88** [comment]
Schelling will be recoded with the "new" style!
