### ISSUE TITLE
Improvement of getter function.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#73]
https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L418

I guess it will be better to allow someone to check someone else's reward in case the user wants to find out the reward of another user.

```
function checkReward(address _who) constant returns (uint256 _reward) {
        /*
            Withdraw of the amount of the prize (it’s only informational).
            
            @reward         Prize
        */
        var voter = getVoter(_who);
        return voter.rewards;
}
```

**Comment by iFA88** [comment]
Sorry? The function allow to check every one reward balance.
