### ISSUE TITLE
exchange.sol has its own variant of the owned.sol contract, ico.sol contains a third implementation of this check

### ISSUE THREAD

**Issue by pyskell** [CORIONplatform/solidity#79]
Should this be the case? Are there supposed to be two possible owners, one for the `exchange`, and one for the `tokenDB`?

Even in such a case couldn't this be abstracted to use the same contract via OpenZeppelin's [Ownable contract](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ownership/Ownable.sol)?

Related to this the code in both contracts are not currently equivalent.

**Comment by pyskell** [comment]
Related to this, `ico.sol` has `require(msg.sender == owner);` instead of either of the other two options I mentioned previously.

**Comment by iFA88** [comment]
Exchange is under development! This is an "third party" contract which offers COR/ETC trading for anyone.
For ICO owner would be temporarily the foundation.
