### ISSUE TITLE
modules.length++ does not do anything in addModule() in the base case in moduleHandler.sol, and modules[id] = input may not work as intended

### ISSUE THREAD

**Issue by pyskell** [CORIONplatform/solidity#82]
At the end of `addModule()` is the following code:

```
        if ( ! found ) {
            id = modules.length;
            modules.length++;
        }
        modules[id] = input;
```

`modules.length++` will not increase the size of the array and is unnecessary.

According to [this stackoverflow question](https://ethereum.stackexchange.com/a/11537) you should likely be using `modules.push()` since `modules` does not have a declared size.

**Comment by gundas** [comment]
Actually the code works as expected:

1. `modules.length++`  increases the size of the array [as documented](http://solidity.readthedocs.io/en/develop/types.html#members)
2. `input` is assigned to either the newly added last element of the array (in case not found)  or to the found location in the array.
