### ISSUE TITLE
Anyone can mint Premium tokens during ICO

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#83]
I think that during the **ICO** period anyone can call **Premium** contract **mint** method  specifying the desired owner address and the amount of  tokens to mint, because the check in **mint** function is not correct:

> require( msg.sender == icoAddr || isICO );

should be && instead of ||

Additionally the private _mint method does not have checks on the caller.

Does this qualify for the bounty as a Critical bug (since it allows unauthorized creation of Premium tokens) ?

**Comment by iFA88** [comment]
Thank you very much! I will reply you later!

**Comment by iFA88** [comment]
Hi, we have fixed this bug. Please contact with CEO on attila@corion.io . Thank you!
