### ISSUE TITLE
ICO contract setInterestDB minor issue?

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#85]
If I am not mistaken, the following scenario could happen with the **setInterestDB** method in **ICO** contract:

1. All the money are transferred out of an account **X**, thus the **InterestDB** **amount** is set to **0** and **empty** is set to **true**
2. A few blocks later (or on the same block if transfer to contract refund happens) the same account **X** receives some new funds. 

**Result** - if the **_num** (calculated as _(block.number - startBlock) / interestBlockDelay_ ) happens to  be the same in both **setInterestDB** calls above, the entry of the **InterestDB** for that account and for that **_num** will have **amount** bigger than 0 and **empty** = true.  This will result in incorrect interest calculation.

The fix should be to also set **empty** to false explicitly, o re-think the use of **empty**.

```
        if ( balance == 0 ) { 
            interestDB[addr][_num].empty = true;
        } **else {
            interestDB[addr][_num].empty = false;
        }**

```

**Comment by iFA88** [comment]
If the user transfer every CORIONS from his/her account then the `empty` will be `true`. Later, if he/she got any amount of CORION then would be `empty = false`.
If you check the interest calculation, you can see how thats work: https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L132-L149

**Comment by gundas** [comment]
Yes, but that will work only if the user gets CORION again **after** the `interestBlockDelay` blocks - so a new value of `_num` is calculated. If there are less than `interestBlockDelay` blocks between the two user actions (spend and  receive CORION), then the `_num` will be the same, and subsequently `empty` will be left to `true`.

**Comment by iFA88** [comment]
Yes you have right, we need put an else for false to the `setInterestDB`!

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/89
