### ISSUE TITLE
ICO closing - pre-ico premium tokens are ignored when calculating 20% and 49% for Foundation

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#86]
The **closeICO()** method makes sure that **Foundation** receives between 20% and 49% of the Premium tokens. However, only the Premium tokens released during **ICO** are taken into account  - the Premium tokens created as a part of genesis block are ignored, thus the calculations of 20% and 49% are not really correct - they are lower than intended (documented).

**Comment by iFA88** [comment]
Thank you for your support. Nice catch, fixed!
