### ISSUE TITLE
Documentation: ICO contract closeICO() - the minimum 20% Premium tokens release to Foundation is not documented

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#87]
The Business whitepaper specifies the the Foundation cannot have more than 49% of the Premium tokens. However, it does not explicitly specify that Foundation's Premium tokens share is less than 20%, an  extra **emission** of Premium tokens will be made and awarded to the Foundation - thus, strictly speaking, it breaks the rule that one Premium token is issued for each 5000 COR.

**Comment by ItsmeeBosslady** [comment]
That's interesting, and where can you see the amount of premium tokens issued in order to calculate?

**Comment by Zomb2e** [comment]
We`ve modified the business requirements, but we didn`t change it in the white paper. We are on it to make the documentation and the developement consistent.
