### ISSUE TITLE
Documentation: ICO closing implementation does not distribute Premium tokens as documented

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#88]
Risking to state the very obvious, but the business whitepaper claims:
```
The Foundation is not allowed to hold more than 49% of the Premium Tokens. Tokens
over 49% will be distributed to the ICO participants who invested the closest to 5000
CORION coin.
```
Currently the distribution of tokens over 49% to the ICO participants is not implemented in **ICO** contract **closeICO()** method.

**Comment by iFA88** [comment]
On the master branch: https://github.com/CORIONplatform/solidity/blob/master/ico.sol#L220-L245

**Comment by gundas** [comment]
Maybe I misunderstand something, but the code on master branch goes not distribute Premium tokens to the ICO participants who invested the **closest** to 5000 CORION coin in case the Foundation's share is reduced to 49%, as stated in white paper.
