### ISSUE TITLE
moduleHandler: callReplaceCallback might replace wrong module

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#91]
[https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L175-L176](https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L175-L176)

if module is not found by the name (`_found` is not checked), then unrelated module with '_id=0' will be replaced with a new one.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/commit/14b5dbaf281997c4ac002027d5ff5b2a8027eb1e

**Comment by gundas** [comment]
It should check the `_found` not the `_id`  - now the module with `_id=0` cannot be replaced.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/pull/99
