### ISSUE TITLE
moduleHandler: callDisableCallback might disable wrong module

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#92]
[https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L232-L233](https://github.com/CORIONplatform/solidity/blob/master/moduleHandler.sol#L232-L233)

if module is not found by the name (`_found` is not checked), then some other module with '_id=0' will be disabled.

**Comment by iFA88** [comment]
https://github.com/CORIONplatform/solidity/commit/c213f90016d84a877b1fa84ac869e2862df33ed7
