### ISSUE TITLE
question: purpose of allowance 

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#97]
Hello,

As implemented, allowance does not enforce any commitment that allowance **receiver** will be able to get the CORION - the **owner** might create multiple allowances to difference receivers (kind of "doublespend") or empty his account after creating the allowances before the allowances are used.

What is the business use case of allowance feature?

**Comment by Dexaran** [comment]
I've suggested to exclude an `approval` mechanism from the token and premium contract multiple times. Approves doesn't introduce any  functional that can not be implemented through fallback function handling.

**Comment by iFA88** [comment]
You can not transfer more token as the owner has.
`A` has 1000 token and allows `B` and `C` to withdraw 1000 token. `B`+`C` can not withdraw more than 1000 token if the `A` doesn't have that.
https://github.com/CORIONplatform/solidity/blob/master/token.sol#L327-L335

**Comment by gundas** [comment]
Yes, that was exactly my question - allowance does not provide any guarantee for `B` and `C` recipient that there will be enough funds at `A`. So why would  `B` and `C` use the allowances? What is the business case?

Unless of course they fully trust `A`  - but then they could just as well trust that `A` makes direct transfers to 'B' and 'C'.
